### ISSUE TITLE
CSConfig failed during configuration of feature Staging Service (Feature.MS.CS.CsStaging). 

### ISSUE THREAD

**Issue by hetaldave** [Sitecore/Sitecore.Demo.Retail#81]
I get the following error while running the install-commerce-server.ps1 script. What do I do?

CSConfig failed during configuration of feature Staging Service (Feature.MS.CS.CsStaging).
[07:19:48 ERROR] Exception occured during feature configuration: CommerceServer.Core.Internal.Config.ConfigurationException: Access is denied ---> System.ComponentModel.Win32Exception: Access is denied
   --- End of inner exception stack trace ---
   at CommerceServer.Core.Internal.Config.NTUserImpersonate.Start(NTServiceCredentialXmlElement serviceSettings)
   at CommerceServer.Core.Internal.Config.StagingConfig.SaveReplicationCredentials(NTServiceCredentialXmlElement serviceSettings)
   at CommerceServer.Core.Internal.Config.StagingConfig.Configure()
   at CommerceServer.Core.Internal.Config.ConfigurationDriver.ConfigureHelper(List`1 orderedListOfFeatures).

**Comment by jflsitecore** [comment]
Are you running the script(s) as administrator?

**Comment by hetaldave** [comment]
Yes. I also tried to run the CE-Install-Commerce-Server task from Visual Studio but got the same results.

**Comment by hetaldave** [comment]
The error gets reported during configuring the staging service feature part of step 5 (Run commerce Server Configuration)

**Comment by jflsitecore** [comment]
Are you installing this on a Domain controller or in Azure?
Apparently some of the required windows groups don't exist in those environments

**Comment by hetaldave** [comment]
Nope. Just the standard install on my machine.

**Comment by Nospamas** [comment]
Ran into this issue and re-ran my script for adding the necessary windows features with success. Suspect this might specifically be due to the Windows Identity Foundation feature being missing on the target machine. Double check the requirements document called `Server2012_FeaturesRequired.txt`

**Comment by jeanfrancoislarente** [comment]
Closing due to lack of activity

**Comment by gleb1505** [comment]
I have fixed this issue by changing of csconfig.xml file. Chect it in https://stackoverflow.com/questions/47199832/sitecore-commerce-demo-site-sitecore-demo-retail-set-up-issues/47201149#47201149
