### ISSUE TITLE
Staging Service fails to install

### ISSUE THREAD

**Issue by hetaldave** [Sitecore/Sitecore.Demo.Retail#84]
I have been trying to install the Demo solution and haven't been able to run the commerce Server install step successfully with the **HabitatRuntimeUser**. I am trying to run this install on my machine that is member of my company's domain network. I also tried to install with options to exclude Staging service feature and also the Performance counter feature - since that was causing issues too.

However, when I change the user account on the commerce config json file to my domain account, it works and installs Commerce Server and all the feature successfully.

And I have been running all installs as admin in VS, Command window and Powershell
The specs for my Install - 
Windows 10 Enterprise
SQL Server 2014
VS 2015

The errors I see in the Event Viewer after the Commerce Server Install fails are as below - 
Exception occured during feature configuration: CommerceServer.Core.Internal.Config.ConfigurationException: Access is denied ---> System.ComponentModel.Win32Exception: Access is denied
   --- End of inner exception stack trace ---
   at CommerceServer.Core.Internal.Config.NTUserImpersonate.Start(NTServiceCredentialXmlElement serviceSettings)
   at CommerceServer.Core.Internal.Config.StagingConfig.SaveReplicationCredentials(NTServiceCredentialXmlElement serviceSettings)
   at CommerceServer.Core.Internal.Config.StagingConfig.Configure()
   at CommerceServer.Core.Internal.Config.ConfigurationDriver.ConfigureHelper(List`1 orderedListOfFeatures).

**Comment by jeanfrancoislarente** [comment]
@hetaldave did you get this resolved or did you give up? 

I think I remember this issue being caused by an obscure missing prerequisite.
